alter setAgendaStatus query to insert new AgendaStatusActivity
kanselarij-vlaanderen/agenda-approve-service pull request #37
Opened 2023-04-06 08:50 UTC by StuyckRuben

2023-04-11 15:38 UTC, sergiofenoll requested changes

2023-04-11 15:38 UTC, sergiofenoll commented on repository/agenda-general.js
> +    ${sparqlEscapeUri(agendaStatusActivity)} a ext:AgendaStatusActivity ;
Dit heeft ook een `mu:uuid` nodig, anders kan mu-cl-resources het niet oppikken. Zelfde uuid als degene die je in de URI zet.

2023-04-20 13:14 UTC, ValenberghsSven approved these changes
made small changes (prov:Activity was not being added automatically)
Seems good

2023-04-20 14:45 UTC, ValenberghsSven commented
Made some more changes after approving.
New designagendas from this service did not have the status-activity, those created in frontend do (not specifically requested)
Also added a deletion of all activities if the agenda is deleted.
Extracted the code for inserting the status-activity to a separate function because we use it in 2 locations.

2023-04-21 07:53 UTC, sergiofenoll approved these changes

2023-04-21 13:06 UTC, merged